= Test Front Page
:page-layout: page_front



[.cards]
****

// Add cards as you see fit below. Try not to repeat consecutive colors.

[.card.blue]
.icon:edit[] Fast & Smart Editing
Apache NetBeans is much more than a text editor. It highlights source code xref:kb/docs/java/editor-codereference.adoc[syntactically and semantically], lets you easily xref:kb/docs/java/editor-inspect-transform.adoc[refactor code], with a range of handy and powerful tools.

[.card.green]
.icon:wrench[] Java, JavaScript, PHP, HTML5, CSS, and More
Apache NetBeans provides editors, wizards, and templates to help you create applications in xref:kb/docs/java/index.adoc[Java], xref:kb/docs/php/index.adoc[PHP] and many other languages.

[.card.magenta]
.icon:download[] Cross Platform
Apache NetBeans can be xref:download/index.adoc[installed] on all operating systems that support Java, i.e, Windows, Linux, Mac OSX and BSD. Write Once, Run Anywhere, applies to NetBeans too. 

[.card.green]
.icon:users[] Join us
Subscribe to our xref:community/mailing-lists.adoc[mailing lists], or follow us in link:https://twitter.com/netbeans[Twitter], link:https://tinyurl.com/netbeans-slack-signup/[Slack], link:https://www.facebook.com/NetBeans[FaceBook] or link:https://www.youtube.com/user/netbeansvideos[YouTube].

[.card.magenta]
.icon:arrow-right[] Participate
See how you can participate by xref:participate/submit-pr.adoc[submitting pull requests], xref:participate/report-issue.adoc[filing issues], or joining the link:https://cwiki.apache.org/confluence/display/NETBEANS/NetCAT[NetCAT] program.

[.card.blue]
.icon:book[] Learn
We are currently reviewing the tutorials. See how you can xref:kb/docs/contributing.adoc[help us] review the xref:kb/docs/java/index.adoc[Java] and xref:kb/docs/php/index.adoc[PHP] tutorials.
