'use strict'

module.exports = () => {
  return  [
    { id: '_getting_started', name: 'Getting Started' },
    { id: '_tutorials_and_important_starting_points', name: 'Tutorials and important starting points' },
    { id: '_getting_support_where_to_find_examples', name: 'Getting support, where to find examples' },
    { id: '_application_lifecycle_and_hooks', name: 'Application Lifecycle and Hooks' },
    { id: '_development_issues_module_basics_and_classpath_issues_and_information_about_rcpplatform_application_configuration', name: 'Development issues, module basics and classpath issues, and information about RCP/Platform application configuration' },
    { id: '_mavenized_builds', name: 'Mavenized Builds' },
    { id: '_configuration_how_modules_install_things', name: 'Configuration: How Modules Install Things' },
    { id: '_when_there_are_multiple_ways_to_do_something', name: 'When There Are Multiple Ways To Do Something...' },
    { id: '_actions_how_to_add_things_to_files_folders_menus_toolbars_and_more', name: 'Actions: How to add things to Files, Folders, Menus, Toolbars and more' },
    { id: '_key_bindings', name: 'Key Bindings' },
    { id: '_lookup', name: 'Lookup' },
    { id: '_files_and_data_objects', name: 'Files and Data Objects' },
    { id: '_converting_between_common_data_types_and_finding_things', name: 'Converting between common data types and finding things' },
    { id: '_editor_and_edited_files', name: 'Editor and Edited Files' },
    { id: '_file_management_within_the_ideapplication', name: 'File Management (within the IDE/Application)' },
    { id: '_module_system', name: 'Module System' },
    { id: '_nodes_and_explorer', name: 'Nodes and Explorer' },
    { id: '_tasks_and_progressbar', name: 'Tasks and Progressbar' },
    { id: '_command_line_parsing', name: 'Command Line Parsing' },
    { id: '_threading', name: 'Threading' },
    { id: '_creating_a_custom_programming_language', name: 'Creating a Custom Programming Language' },
    { id: '_settings', name: 'Settings' },
    { id: '_window_system', name: 'Window System' },
    { id: '_dialogs_api', name: 'Dialogs API' },
    { id: '_xml_multiview_api', name: 'XML Multiview API' },
    { id: '_project_handling', name: 'Project Handling' },
    { id: '_project_types', name: 'Project Types' },
    { id: '_versioning', name: 'Versioning' },
    { id: '_printing', name: 'Printing' },
    { id: '_html_browser', name: 'HTML Browser' },
    { id: '_wizards_and_templates', name: 'Wizards and Templates' },
    { id: '_properties_and_propertysheet', name: 'Properties and PropertySheet' },
    { id: '_output_window', name: 'Output Window' },
    { id: '_using_enterprise_resources_from_netbeans_module', name: 'Using Enterprise Resources from NetBeans module' },
    { id: '_running_and_writing_tests', name: 'Running and Writing tests' },
    { id: '_branding_your_application', name: 'Branding your application' },
    { id: '_authentication_and_authorization_in_platform_apps', name: 'Authentication and Authorization in Platform Apps' },
    { id: '_logging_and_error_handling', name: 'Logging and Error Handling' },
    { id: '_javahelp', name: 'JavaHelp' },
    { id: '_look_and_design', name: 'Look and Design' },
    { id: '_deploying_changes_through_autoupdate_and_using_autoupdate_api', name: 'Deploying Changes through AutoUpdate and using Autoupdate API' },
    { id: '_deployment_using_installers_nbi', name: 'Deployment using installers / NBI' },
    { id: '_programmatic_access_to_java_sources', name: 'Programmatic access to Java Sources' },
    { id: '_when_things_go_wrong_troubleshooting', name: 'When things go wrong: Troubleshooting' },
    { id: '_licensing_issues', name: 'Licensing Issues' },
    { id: '_using_sounds', name: 'Using Sounds' }];

}
